name: food_cost_calculator_3_0
description: A new Flutter project.
publish_to: 'none'

version: 3.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_localizations:   # 추가
    sdk: flutter           # 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

