name: website
description: "website"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers:  ^ 4.0.4
  # http: ^1.2.1
  firebase_core: ^2.25.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  firebase_analytics: ^10.8.5
  firebase_analytics_web: ^0.5.5+17
  firebase_core_web: ^2.11.3
  firebase_auth: ^4.17.3
  firebase_auth_web: ^5.9.3
  firebase_app_check: ^0.2.1+12
  cloud_functions: ^4.6.5
  firebase_storage: ^11.6.4
  firebase_storage_web: ^3.6.21
  flutter_riverpod: ^2.4.10
  cloud_firestore: ^4.15.3
  cloud_firestore_web: ^3.10.3
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+2
  rxdart: ^0.27.7
  build_test: ^2.1.0
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.1


flutter:
  assets:
    - lib/images/


  uses-material-design: true


