name: free_caption_on_video_website
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  file_picker: ^9.0.0
  idb_shim: ^2.6.2
  http: ^1.3.0
  flutter_colorpicker: ^1.0.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_core_web: ^2.21.1
  cloud_firestore: ^5.6.5
  animations: ^2.0.11
  cloud_firestore_web: ^4.4.5
  flutter_riverpod: ^2.6.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
assets:
  - lib/assets/.env  # 정확한 경로로 수정
flutter:

  uses-material-design: true
