import 'package:flutter/material.dart';
import 'dart:math';

List<Color> colors = [
  Colors.blue,
  Colors.red,
  Colors.orange,
  Colors.yellow,
  Colors.green,
  Colors.indigo,
  Colors.purple,
  Colors.cyan,
  Colors.teal,
  Colors.pink,
  Colors.amber,
  Colors.lime,
  Colors.brown,
  Colors.grey,
  Colors.blueGrey,
  Colors.deepOrange,
  Colors.deepPurple,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.orangeAccent,
  Colors.yellowAccent,
  Colors.greenAccent,
  Colors.blueAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.redAccent,
  Colors.pinkAccent,
  Colors.tealAccent,
  Colors.cyanAccent,
  Colors.limeAccent,
  Colors.amberAccent,
  Colors.lightBlueAccent,
  Colors.lightGreenAccent,
  Colors.deepOrangeAccent,
  Colors.deepPurpleAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.yellow,
  Colors.pink,
  Colors.amber,
  Colors.lime,
  Colors.brown,
  Colors.grey,
  Colors.blueGrey,
  Colors.deepOrange,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.cyan,
  Colors.teal,
  Colors.pink,
  Colors.amber,
  Colors.lime,
  Colors.brown,
  Colors.grey,
  Colors.blueGrey,
  Colors.deepOrange,
  Colors.deepPurple,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.orangeAccent,
  Colors.yellowAccent,
  Colors.greenAccent,
  Colors.blueAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.redAccent,
  Colors.pinkAccent,
  Colors.tealAccent,
  Colors.cyanAccent,
  Colors.limeAccent,
  Colors.amberAccent,
  Colors.lightBlueAccent,
  Colors.lightGreenAccent,
  Colors.deepOrangeAccent,
  Colors.deepPurpleAccent,
  Colors.indigoAccent,
  Colors.purpleAccent,
  Colors.red,
  Colors.orange,
  Colors.yellow,
  Colors.green,
  Colors.blue,
  Colors.indigo,
  Colors.purple,
  Colors.grey,
  Colors.brown,
  Colors.pink,
  // 필요한 만큼 다른 색상을 추가하세요.
];

Random random = Random();

Color getRandomColor() {
  return colors[random.nextInt(colors.length)];
}

Color getSettledColor(int index) {
  return colors[index % colors.length];
}