// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4CM4h5Yb8ZCO__YJ47qOs-ojGyp4Py_s',
    appId: '1:618851710711:web:2abe66a9f078076c8ac5f2',
    messagingSenderId: '618851710711',
    projectId: 'freedomcompass-920ee',
    authDomain: 'freedomcompass-920ee.firebaseapp.com',
    storageBucket: 'freedomcompass-920ee.appspot.com',
    measurementId: 'G-DCSBRQX1HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjEAABV2F7DeE-ErnajZ1DMLUhFIFXCGw',
    appId: '1:618851710711:android:88ace0cd69dfed9b8ac5f2',
    messagingSenderId: '618851710711',
    projectId: 'freedomcompass-920ee',
    storageBucket: 'freedomcompass-920ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPTku1kZ8cpvoNloX_BnnSdxRmKtFwVcc',
    appId: '1:618851710711:ios:29184fcb29f55b5a8ac5f2',
    messagingSenderId: '618851710711',
    projectId: 'freedomcompass-920ee',
    storageBucket: 'freedomcompass-920ee.appspot.com',
    androidClientId: '618851710711-10dh9ql6v153t0iqaa1drdujjncusm6e.apps.googleusercontent.com',
    iosClientId: '618851710711-49qif2pg2gvhsovf3e7peo92ncjvcoic.apps.googleusercontent.com',
    iosBundleId: 'com.example.freedomcompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPTku1kZ8cpvoNloX_BnnSdxRmKtFwVcc',
    appId: '1:618851710711:ios:29184fcb29f55b5a8ac5f2',
    messagingSenderId: '618851710711',
    projectId: 'freedomcompass-920ee',
    storageBucket: 'freedomcompass-920ee.appspot.com',
    androidClientId: '618851710711-10dh9ql6v153t0iqaa1drdujjncusm6e.apps.googleusercontent.com',
    iosClientId: '618851710711-49qif2pg2gvhsovf3e7peo92ncjvcoic.apps.googleusercontent.com',
    iosBundleId: 'com.example.freedomcompass',
  );
}
