name: food_cost_calculator_3_0
description: A new Flutter project.
publish_to: 'none'

version: 2.0.0
# 구글에서 요구하는 그 앱의 버전.

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  fl_chart: ^0.66.2
  shared_preferences: ^2.1.1
  firebase_app_check: ^0.2.1+14
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.1.3
  url_launcher: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/image/


