name: freedom_compass
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.2.1+8
  firebase_app_check_platform_interface: ^0.1.0+10
  firebase_app_check_web: ^0.1.0+10
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

